---
name: Skript
author: 
  - Njol
  - Mirreski
  - bensku
  - TheBentoBox
  - FranKusmiruk
  - ShaneBeee
  - Blueyescat
  - JRoy
  - Nicofisi
  - APickledWalrus
  - xXAndrew28Xx
  - Syst3ms
  - TheLimeGlass
  - Pikachu920
  - Sashie
  - Wealthyturtle
  - OfficialDonut
  - eyesniper2
  - Gumbraise
website: 
  - https://skriptlang.github.io/Skript
  - https://kellis.fr/
description: Customize Minecraft's mechanics with simple scripts written in plain English sentences.
version: 2.4-dev1
main: Gumbraise\Skript
api:
- 3.0.0-ALPHA5
commands:
  skript:
        description: Skript's main command. Type '/skript help' for more information.
        aliases: [sk]
        permission: skript.admin
        usage: /skript help
permissions:
    skript.*:
        default: false
        children:
            skript.effectcommands: true
            skript.admin: true
    skript.effectcommands:
        default: false
        description: Allows to use effects as commands, e.g. '!set health to 10'
    skript.admin:
        default: op
        description: Allows to use administrative commands and to recieve notifications of new versions.
...
